//! HTTP-based tool executor for server-side tool calling.
//!
//! [`HttpToolExecutor`] implements `onwards::ToolExecutor` by POSTing tool arguments as JSON to
//! a configured HTTP endpoint.  It is constructed per-request with the resolved tool definitions
//! for that particular request (deployment × group intersection).
//!
//! # Per-request tool resolution
//!
//! Because onwards holds a *single* `Arc<dyn ToolExecutor>` in its shared `AppState`, making it
//! per-request requires an indirection.  We use a `DashMap` inside `PerRequestToolRegistry` keyed
//! by a per-request UUID that is:
//!
//! 1. Generated by the [`tool_injection`] middleware.
//! 2. Written into the registry alongside the resolved `ToolDefinition` map.
//! 3. Forwarded to onwards via a private request header (`x-dw-tool-request-id`).
//! 4. Read back inside `ToolExecutor::execute` from `tokio::task_local!` storage (set by the
//!    middleware scope).
//!
//! The registry cleans up its entry once the request completes (RAII via `scopeguard`).
//!
//! # Analytics
//!
//! Each tool call records a `tool_call_analytics` row via a fire-and-forget background write.

use async_trait::async_trait;
use chrono::Utc;
use dashmap::DashMap;
use onwards::traits::{ToolError, ToolExecutor};
use serde_json::Value;
use sqlx::PgPool;
use std::collections::HashMap;
use std::sync::Arc;
use std::time::Instant;
use tracing::{info_span, instrument, Instrument};
use uuid::Uuid;

// ---------------------------------------------------------------------------
// Per-tool configuration
// ---------------------------------------------------------------------------

/// Per-tool configuration resolved from the database.
#[derive(Debug, Clone)]
pub struct ToolDefinition {
    /// URL to POST tool arguments to.
    pub url: String,
    /// Optional Bearer token for the `Authorization` header.
    pub api_key: Option<String>,
    /// HTTP request timeout in seconds.
    pub timeout_secs: u64,
    /// Foreign key into `tool_sources` for analytics.
    pub tool_source_id: Uuid,
}

/// Full set of tools resolved for a single request.
#[derive(Debug, Clone)]
pub struct ResolvedToolSet {
    /// Resolved tool definitions: name → config.
    pub tools: HashMap<String, ToolDefinition>,
    /// Tool source metadata for schema injection: name → (description, parameters).
    pub metadata: HashMap<String, (Option<String>, Option<Value>)>,
}

impl ResolvedToolSet {
    pub fn new(
        tools: HashMap<String, ToolDefinition>,
        metadata: HashMap<String, (Option<String>, Option<Value>)>,
    ) -> Self {
        Self { tools, metadata }
    }

    pub fn is_empty(&self) -> bool {
        self.tools.is_empty()
    }

    /// Build the OpenAI tool schema array from this resolved tool set.
    ///
    /// Each entry looks like:
    /// ```json
    /// {"type": "function", "function": {"name": "...", "description": "...", "parameters": {...}}}
    /// ```
    pub fn to_openai_schemas(&self) -> Vec<Value> {
        self.tools
            .keys()
            .map(|name| {
                let (description, parameters) = self.metadata.get(name).cloned().unwrap_or((None, None));

                let mut function = serde_json::json!({"name": name});

                if let Some(desc) = description {
                    function["description"] = Value::String(desc);
                }

                if let Some(params) = parameters {
                    function["parameters"] = params;
                }

                serde_json::json!({"type": "function", "function": function})
            })
            .collect()
    }
}

// ---------------------------------------------------------------------------
// Per-request registry
// ---------------------------------------------------------------------------

/// Thread-safe registry mapping request-IDs to their resolved tool sets.
///
/// Shared as `Arc<PerRequestToolRegistry>` in `AppState`.
#[derive(Debug, Default)]
pub struct PerRequestToolRegistry {
    entries: DashMap<Uuid, Arc<ResolvedToolSet>>,
}

impl PerRequestToolRegistry {
    pub fn new() -> Self {
        Self::default()
    }

    /// Insert a resolved tool set for `request_id`.
    pub fn insert(&self, request_id: Uuid, tool_set: ResolvedToolSet) {
        self.entries.insert(request_id, Arc::new(tool_set));
    }

    /// Remove the entry for `request_id` (called on request completion).
    pub fn remove(&self, request_id: Uuid) {
        self.entries.remove(&request_id);
    }

    /// Look up the tool set for `request_id`.
    pub fn get(&self, request_id: Uuid) -> Option<Arc<ResolvedToolSet>> {
        self.entries.get(&request_id).map(|e| e.clone())
    }
}

// ---------------------------------------------------------------------------
// HttpToolExecutor
// ---------------------------------------------------------------------------

/// Global `ToolExecutor` registered in the onwards `AppState`.
///
/// Each call resolves the tool definitions from the per-request registry using the request ID
/// stored in the `CURRENT_TOOL_REQUEST_ID` task-local.
pub struct HttpToolExecutor {
    registry: Arc<PerRequestToolRegistry>,
    client: reqwest::Client,
    pool: Option<Arc<PgPool>>,
}

impl std::fmt::Debug for HttpToolExecutor {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("HttpToolExecutor").finish()
    }
}

// Task-local storage for the current request ID.
tokio::task_local! {
    pub static CURRENT_TOOL_REQUEST_ID: Option<Uuid>;
}

impl HttpToolExecutor {
    pub fn new(registry: Arc<PerRequestToolRegistry>, client: reqwest::Client, pool: Option<Arc<PgPool>>) -> Self {
        Self { registry, client, pool }
    }

    fn get_current_tool_set(&self) -> Option<Arc<ResolvedToolSet>> {
        let request_id = CURRENT_TOOL_REQUEST_ID.try_with(|id| *id).ok()??;
        self.registry.get(request_id)
    }
}

#[async_trait]
impl ToolExecutor for HttpToolExecutor {
    #[instrument(skip(self, arguments), fields(tool.name = %tool_name), err)]
    async fn execute(
        &self,
        tool_name: &str,
        _tool_call_id: &str,
        arguments: &Value,
    ) -> Result<Value, ToolError> {
        let tool_set = self.get_current_tool_set().ok_or_else(|| {
            ToolError::ExecutionError("no tool set available for this request".to_string())
        })?;

        let definition = tool_set.tools.get(tool_name).ok_or_else(|| ToolError::NotFound(tool_name.to_string()))?;

        let started_at = Utc::now();
        let wall_start = Instant::now();

        let span = info_span!(
            "tool.execute",
            tool.name = %tool_name,
            tool.source_id = %definition.tool_source_id,
            http.url = %definition.url,
        );

        let (result, http_status, error_kind) = async {
            let mut req = self
                .client
                .post(&definition.url)
                .timeout(std::time::Duration::from_secs(definition.timeout_secs))
                .json(arguments);

            if let Some(key) = &definition.api_key {
                req = req.header(reqwest::header::AUTHORIZATION, format!("Bearer {key}"));
            }

            match req.send().await {
                Err(e) if e.is_timeout() => {
                    let msg = format!("tool '{}' timed out after {}s", tool_name, definition.timeout_secs);
                    (Err(ToolError::Timeout(msg)), None, Some("timeout"))
                }
                Err(e) => {
                    let msg = format!("tool '{}' connection error: {}", tool_name, e);
                    (Err(ToolError::ExecutionError(msg)), None, Some("connection_error"))
                }
                Ok(resp) => {
                    let status = resp.status();
                    let status_u16 = status.as_u16();

                    if status.is_success() {
                        match resp.bytes().await {
                            Err(e) => {
                                let msg = format!("failed to read tool response body: {e}");
                                (Err(ToolError::ExecutionError(msg)), Some(status_u16), Some("read_error"))
                            }
                            Ok(bytes) => match serde_json::from_slice::<Value>(&bytes) {
                                Ok(json) => (Ok(json), Some(status_u16), None),
                                Err(_) => {
                                    let body = String::from_utf8_lossy(&bytes).into_owned();
                                    (Ok(serde_json::json!({"result": body})), Some(status_u16), None)
                                }
                            },
                        }
                    } else {
                        let body = resp.text().await.unwrap_or_default();
                        let msg = format!("HTTP {}: {}", status_u16, body);
                        (Err(ToolError::ExecutionError(msg)), Some(status_u16), Some("http_error"))
                    }
                }
            }
        }
        .instrument(span)
        .await;

        let duration_ms = wall_start.elapsed().as_millis() as i64;
        let success = result.is_ok();
        let http_status_i32 = http_status.map(|s| s as i32);
        let tool_source_id = definition.tool_source_id;
        let tool_name_owned = tool_name.to_string();
        let error_kind_owned = error_kind.map(|s| s.to_string());

        // Fire-and-forget analytics write.
        if let Some(pool) = &self.pool {
            let pool = pool.clone();
            tokio::spawn(async move {
                let res = sqlx::query!(
                    r#"
                    INSERT INTO tool_call_analytics
                        (analytics_id, tool_source_id, tool_name, started_at, duration_ms,
                         http_status_code, success, error_kind)
                    VALUES (NULL, $1, $2, $3, $4, $5, $6, $7)
                    "#,
                    tool_source_id,
                    tool_name_owned,
                    started_at,
                    duration_ms,
                    http_status_i32,
                    success,
                    error_kind_owned.as_deref(),
                )
                .execute(&*pool)
                .await;

                if let Err(e) = res {
                    tracing::warn!(error = %e, "Failed to record tool_call_analytics");
                }
            });
        }

        result
    }

    fn can_handle(&self, tool_name: &str) -> bool {
        let Some(tool_set) = self.get_current_tool_set() else { return false };
        tool_set.tools.contains_key(tool_name)
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use wiremock::matchers::{header, method, path};
    use wiremock::{Mock, MockServer, ResponseTemplate};

    fn make_registry_and_executor(
        tool_name: &str,
        server_url: &str,
        api_key: Option<String>,
    ) -> (Arc<PerRequestToolRegistry>, HttpToolExecutor, Uuid) {
        let registry = Arc::new(PerRequestToolRegistry::new());
        let client = reqwest::Client::new();
        let executor = HttpToolExecutor::new(registry.clone(), client, None);

        let request_id = Uuid::new_v4();
        let mut tools = HashMap::new();
        tools.insert(
            tool_name.to_string(),
            ToolDefinition {
                url: format!("{server_url}/tool"),
                api_key,
                timeout_secs: 5,
                tool_source_id: Uuid::nil(),
            },
        );
        registry.insert(request_id, ResolvedToolSet::new(tools, HashMap::new()));

        (registry, executor, request_id)
    }

    async fn with_task_local<F, Fut>(request_id: Uuid, f: F) -> Fut::Output
    where
        F: FnOnce() -> Fut,
        Fut: std::future::Future,
    {
        CURRENT_TOOL_REQUEST_ID.scope(Some(request_id), f()).await
    }

    #[tokio::test]
    async fn test_execute_returns_json_body() {
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .and(path("/tool"))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({"result": 42})))
            .mount(&server)
            .await;

        let (_registry, executor, req_id) = make_registry_and_executor("test_tool", &server.uri(), None);
        let result = with_task_local(req_id, || async {
            executor.execute("test_tool", "id1", &serde_json::json!({"x": 1})).await
        })
        .await;

        assert!(result.is_ok());
        assert_eq!(result.unwrap(), serde_json::json!({"result": 42}));
    }

    #[tokio::test]
    async fn test_execute_wraps_non_json_body() {
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .and(path("/tool"))
            .respond_with(ResponseTemplate::new(200).set_body_string("hello world"))
            .mount(&server)
            .await;

        let (_registry, executor, req_id) = make_registry_and_executor("test_tool", &server.uri(), None);
        let result = with_task_local(req_id, || async {
            executor.execute("test_tool", "id1", &serde_json::json!({})).await
        })
        .await;

        assert!(result.is_ok());
        assert_eq!(result.unwrap(), serde_json::json!({"result": "hello world"}));
    }

    #[tokio::test]
    async fn test_execute_sends_auth_header() {
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .and(path("/tool"))
            .and(header("authorization", "Bearer my-secret"))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({"ok": true})))
            .mount(&server)
            .await;

        let (_registry, executor, req_id) =
            make_registry_and_executor("test_tool", &server.uri(), Some("my-secret".to_string()));

        let result = with_task_local(req_id, || async {
            executor.execute("test_tool", "id1", &serde_json::json!({})).await
        })
        .await;

        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_execute_returns_error_on_4xx() {
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .and(path("/tool"))
            .respond_with(ResponseTemplate::new(400).set_body_string("bad request"))
            .mount(&server)
            .await;

        let (_registry, executor, req_id) = make_registry_and_executor("test_tool", &server.uri(), None);
        let result = with_task_local(req_id, || async {
            executor.execute("test_tool", "id1", &serde_json::json!({})).await
        })
        .await;
        assert!(matches!(result, Err(ToolError::ExecutionError(_))));
    }

    #[tokio::test]
    async fn test_execute_returns_error_on_5xx() {
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .and(path("/tool"))
            .respond_with(ResponseTemplate::new(500).set_body_string("internal error"))
            .mount(&server)
            .await;

        let (_registry, executor, req_id) = make_registry_and_executor("test_tool", &server.uri(), None);
        let result = with_task_local(req_id, || async {
            executor.execute("test_tool", "id1", &serde_json::json!({})).await
        })
        .await;
        assert!(matches!(result, Err(ToolError::ExecutionError(_))));
    }

    #[tokio::test]
    async fn test_can_handle_returns_true_for_registered_tools() {
        let registry = Arc::new(PerRequestToolRegistry::new());
        let request_id = Uuid::new_v4();
        let mut tools = HashMap::new();
        tools.insert(
            "my_tool".to_string(),
            ToolDefinition {
                url: "http://example.com".to_string(),
                api_key: None,
                timeout_secs: 5,
                tool_source_id: Uuid::nil(),
            },
        );
        registry.insert(request_id, ResolvedToolSet::new(tools, HashMap::new()));

        let client = reqwest::Client::new();
        let executor = HttpToolExecutor::new(registry, client, None);

        let result = CURRENT_TOOL_REQUEST_ID.scope(Some(request_id), async {
            (executor.can_handle("my_tool"), executor.can_handle("unknown"))
        })
        .await;

        assert!(result.0);
        assert!(!result.1);
    }

    #[tokio::test]
    async fn test_not_found_for_unknown_tool() {
        let registry = Arc::new(PerRequestToolRegistry::new());
        let request_id = Uuid::new_v4();
        registry.insert(request_id, ResolvedToolSet::new(HashMap::new(), HashMap::new()));

        let client = reqwest::Client::new();
        let executor = HttpToolExecutor::new(registry, client, None);

        let result = CURRENT_TOOL_REQUEST_ID.scope(Some(request_id), async {
            executor.execute("unknown", "id1", &serde_json::json!({})).await
        })
        .await;
        assert!(matches!(result, Err(ToolError::NotFound(_))));
    }

    #[test]
    fn test_resolved_tool_set_to_openai_schemas() {
        let mut tools = HashMap::new();
        tools.insert(
            "weather".to_string(),
            ToolDefinition {
                url: "http://example.com".to_string(),
                api_key: None,
                timeout_secs: 30,
                tool_source_id: Uuid::nil(),
            },
        );
        let mut metadata = HashMap::new();
        metadata.insert(
            "weather".to_string(),
            (
                Some("Get the weather".to_string()),
                Some(serde_json::json!({
                    "type": "object",
                    "properties": {"location": {"type": "string"}},
                    "required": ["location"]
                })),
            ),
        );

        let tool_set = ResolvedToolSet::new(tools, metadata);
        let schemas = tool_set.to_openai_schemas();
        assert_eq!(schemas.len(), 1);
        assert_eq!(schemas[0]["type"], "function");
        assert_eq!(schemas[0]["function"]["name"], "weather");
        assert_eq!(schemas[0]["function"]["description"], "Get the weather");
    }

    #[test]
    fn test_tool_set_intersection_logic() {
        // Simulate intersection: deployment has {A, B}, group has {B, C}, result is {B}
        let deployment_tools: std::collections::HashSet<&str> = ["A", "B"].iter().copied().collect();
        let group_tools: std::collections::HashSet<&str> = ["B", "C"].iter().copied().collect();
        let intersection: std::collections::HashSet<&str> =
            deployment_tools.intersection(&group_tools).copied().collect();

        assert_eq!(intersection.len(), 1);
        assert!(intersection.contains("B"));
    }
}
