services:
  postgres:
    ports:
      - "5433:5432"
    healthcheck:
      disable: true

  waycast:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgres://waycast:waycast_password@postgres:5432/waycast
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./waycast/src:/app/waycast/src:ro
      - ./waycast/Cargo.toml:/app/waycast/Cargo.toml:ro
      - ./waycast/Cargo.lock:/app/waycast/Cargo.lock
      - ./waycast/migrations:/app/waycast/migrations:ro
      - ./waycast/.sqlx:/app/waycast/.sqlx:ro
      - waycast_target:/app/waycast/target
      - cargo_registry:/usr/local/cargo/registry
      - cargo_git:/usr/local/cargo/git
    depends_on:
      postgres:
        condition: service_started
    healthcheck:
      disable: true

  waycast-frontend:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - BACKEND_URL=http://waycast:3001
    volumes:
      - ./dashboard:/app
      - waycast_frontend_node_modules:/app/node_modules
      - /app/.vite
    develop:
      watch:
        - action: rebuild
          path: ./dashboard/package.json
        - action: rebuild
          path: ./dashboard/Dockerfile

volumes:
  waycast_target:
  waycast_frontend_node_modules:
  cargo_registry:
  cargo_git:

networks:
  default:
    driver: bridge
