services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-waycast}
      POSTGRES_USER: ${POSTGRES_USER:-waycast}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-waycast_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U waycast -d waycast"]
      start_period: 1s
      interval: 1s
      timeout: 3s
      retries: 10

  waycast:
    image: ghcr.io/doublewordai/waycast/waycast:${TAG:-latest}
    pull_policy: ${PULL_POLICY:-always}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - RUST_LOG=debug
      - DATABASE_URL=postgres://waycast:waycast_password@postgres:5432/waycast
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/healthz"]
      start_period: 1s
      interval: 100s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
