services:
  postgres:
    ports:
      - "5433:5432"
    healthcheck:
      disable: true

  dwctl-prod:
    extends:
      file: docker-compose.yml
      service: dwctl
    profiles:
      - prod
    build:
      context: .
      dockerfile: Dockerfile

  dwctl-dev:
    extends:
      file: docker-compose.yml
      service: dwctl
    profiles:
      - dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./dwctl/src:/app/dwctl/src:ro
      - ./dwctl/Cargo.toml:/app/dwctl/Cargo.toml:ro
      - ./dwctl/Cargo.lock:/app/dwctl/Cargo.lock
      - ./dwctl/migrations:/app/dwctl/migrations:ro
      - ./dwctl/.sqlx:/app/dwctl/.sqlx:ro
      - dwctl_target:/app/dwctl/target
      - cargo_registry:/usr/local/cargo/registry
      - cargo_git:/usr/local/cargo/git
    depends_on:
      postgres:
        condition: service_started
    healthcheck:
      disable: true

  dwctl-frontend:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - BACKEND_URL=http://dwctl:3001
    volumes:
      - ./dashboard:/app
      - dwctl_frontend_node_modules:/app/node_modules
      - /app/.vite
    develop:
      watch:
        - action: rebuild
          path: ./dashboard/package.json
        - action: rebuild
          path: ./dashboard/Dockerfile

volumes:
  dwctl_target:
  dwctl_frontend_node_modules:
  cargo_registry:
  cargo_git:

networks:
  default:
    driver: bridge
