services:
  benchmark:
    build:
      context: ./benchmark
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          path: ./benchmark/Cargo.toml
        - action: rebuild
          path: ./benchmark/Cargo.lock
        - action: rebuild
          path: ./benchmark/src

  litellm-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: litellm
      POSTGRES_USER: litellm
      POSTGRES_PASSWORD: litellm_password
    volumes:
      - litellm_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U litellm -d litellm"]
      interval: 5s
      timeout: 3s
      retries: 5

  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    ports:
      - "4000:4000"
    volumes:
      - ./benchmark/litellm_config.yaml:/app/config.yaml:ro
    environment:
      - DATABASE_URL=postgresql://litellm:litellm_password@litellm-postgres:5432/litellm
    command: --config /app/config.yaml --detailed_debug
    depends_on:
      litellm-postgres:
        condition: service_healthy

volumes:
  litellm_postgres_data:

networks:
  default:
    driver: bridge
