# Onwards Pilot Configuration
# This is the default configuration file. Copy to onwards-pilot.production.yaml
# for production settings that include API keys.

# Server configuration
host: "0.0.0.0"
port: 3001

# Database connection
database_url: "postgres://postgres:postgres@localhost:5432/test"

# Admin user email - will be created on first startup
admin_email: "fergus.finn@doubleword.ai"

# Model sources - inference endpoints to connect to
# Uncomment and configure as needed
model_sources:
  # Local development server
  - name: "local"
    url: "http://host.docker.internal:8000"
    sync_interval: "10s"

# Example configurations:
# model_sources:
#   # OpenAI API
#   - name: "openai"
#     url: "https://api.openai.com"
#     api_key: "sk-..."  # Required for model sync
#     sync_interval: "30s"
#
#   # Anthropic API
#   - name: "anthropic"
#     url: "https://api.anthropic.com"
#     api_key: "sk-ant-..."  # Required for model sync
#     sync_interval: "1m"
#
#   # Internal model server (no auth required)
#   - name: "internal"
#     url: "http://internal-models:8080"
#     sync_interval: "5m"
#
#   # Local development server
#   - name: "local"
#     url: "http://localhost:8000"
#     sync_interval: "10s"

# Frontend metadata
metadata:
  region: "UK South"
  organization: "ACME Corp"

# Global secret key for encryption/signing (REQUIRED)
# Generate with: openssl rand -base64 32
# secret_key: "your-secret-key-here"

# Authentication configuration
auth:
  # Native username/password authentication
  native:
    enabled: true # Enable native login system
    allow_registration: true
    password:
      min_length: 8
      max_length: 64
    session:
      timeout: "24h"
      cookie_name: "clay_session"
      cookie_secure: true
      cookie_same_site: "strict"

  # Proxy header authentication (current system)
  proxy_header:
    enabled: false # X-Doubleword-User header auth
    user_field_name: "x-doubleword-user"
    auto_create_users: true

  # Security settings
  security:
    enable_csrf: true
    jwt_expiry: "1h"
    cors:
      allowed_origins:
        - "http://localhost:5173"  # Development frontend (Vite)
        - "https://localhost"      # Local HTTPS
      allow_credentials: true
      max_age: 3600  # Cache preflight requests for 1 hour

# Secret key for jwt signing
secret_key: insecure-change-in-production

# Optional feature toggles
enable_metrics: true # Enable Prometheus metrics endpoint
enable_request_logging: true # Enable request/response logging to database
# Note: Environment variables can override top level setting, as long as they're supplied with the CLAY_ prefix.:
# CLAY_PORT=8080
#
# The exception is DATABASE_URL:
# DATABASE_URL=postgres://prod@db:5432/my_database
#
# For arrays like model_sources, use environment-specific config files
# (e.g., clay_config.production.yaml) rather than env vars.

