-- Drop the two request_templates_g2 indexes that mirror dead legacy shapes.
--
-- Companion to 20260904020000_drop_unused_indexes, which drops
-- idx_request_templates_custom_id and idx_request_templates_model from the
-- legacy table. 20260818000000 created request_templates_g2 with four indexes
-- under the comment "Mirror the legacy read paths so per-file streaming, model
-- grouping, and custom-id lookups keep their index shapes inside each weekly
-- child" — but two of the four shapes it faithfully mirrored have no read path,
-- so the new table inherited the legacy table's dead weight.
--
-- No query filters, groups or orders request_templates(_g2) by `model` alone or
-- by `custom_id`: both columns appear only in INSERT column lists and test
-- helpers. Every production read of g2 keys on file_id (per-file streaming and
-- the per-file model counts) or on created_on (retirement and partition
-- pruning), served by idx_request_templates_g2_file_line,
-- idx_request_templates_g2_file_model and the (created_on, id) primary key. A
-- `WHERE file_id = $1 GROUP BY model` shape is served by file_model, so the
-- standalone model index adds nothing even there.
--
-- Supporting evidence for the same two shapes on the legacy table, measured on
-- the production primary over a 35-day window (2026-09-04): custom_id 0 scans,
-- model 6 scans, across ~135M rows.
--
-- NOT dropped: idx_request_templates_g2_id, added by 20260903000000 for the
-- routed by-id probe. It reads as unused while generation-2 writes are
-- disabled, which is not evidence about the probe.
--
-- Mechanics: both are partitioned indexes, so dropping the parent cascades to
-- every attached child. Because ensure_request_template_partition builds each
-- weekly partition with `LIKE request_templates_g2 INCLUDING ALL`, dropping
-- them here also stops future partitions inheriting them — no change to that
-- function is required. DROP INDEX on a partitioned index cannot be run
-- CONCURRENTLY.

DROP INDEX IF EXISTS idx_request_templates_g2_custom_id;
DROP INDEX IF EXISTS idx_request_templates_g2_model;
