ALTER TABLE users ADD COLUMN IF NOT EXISTS auto_topup_amount REAL DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS auto_topup_threshold REAL DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS auto_topup_payment_id TEXT DEFAULT NULL;
