-- no-transaction
-- Add effective_batch_sla to track the actual SLA tier a batch request was charged at.
--
-- When a request submitted at a higher SLA (e.g. "1h") completes after that window,
-- billing falls through to the next tier (e.g. "24h"). If it completes after all
-- configured windows, it's free. This column records which tier was actually applied.
--
-- Values: the completion_window string of the tariff used (e.g. "1h", "24h"),
--         "free" if the request exceeded all configured windows,
--         NULL for rows written before this migration (not backfilled),
--         or empty string for non-batch requests.
--
-- Nullable to avoid a full-table UPDATE on large http_analytics tables.
-- New rows are always written with a value; old rows remain NULL.
ALTER TABLE http_analytics ADD COLUMN IF NOT EXISTS effective_batch_sla TEXT;
