-- Add effective_batch_sla to track the SLA window a batch request was charged at
-- after waterfall resolution.
--
-- When a request submitted at a higher SLA (e.g. "1h") completes after that window,
-- billing falls through to the next tier (e.g. "24h"). If it completes after all
-- configured windows, it's free. This column records the effective window.
--
-- Values: completion_window string (e.g. "1h", "24h"),
--         "free" if the request exceeded all configured windows,
--         "generic_fallback" if no exact window tariff matched,
--         or "" for non-batch requests.
--
-- NOT NULL DEFAULT '' means non-batch rows are instantly correct without a backfill.
-- Historical batch rows keep effective_batch_sla = '' — when analysing those,
-- treat '' as equivalent to batch_sla (pre-waterfall, every batch request was
-- charged at the submitted SLA tier).
ALTER TABLE http_analytics ADD COLUMN IF NOT EXISTS effective_batch_sla TEXT NOT NULL DEFAULT '';
